### ISSUE TITLE
add proper example

### ISSUE THREAD

**Issue by aster94** [MajicDesigns/MD_Menu#1]
hello marco,

this is not an issue but a suggestion
i just found your library on the arduino forum, i didn't tried it yet
i think that without a simple example many people would found it difficult to use
What do you think about adding a fake example using the serial as display?
maybe the user input could be the serial itself or a rotary encoder or a few buttons

cheers,
bye

**Comment by MajicDesigns** [comment]
Thanks for the suggestion. I'll put it on the (long) list of things to do.
