### ISSUE TITLE
INP_RUN runs code upon selection and then again upon confirm

### ISSUE THREAD

**Issue by bborncr** [MajicDesigns/MD_Menu#11]
The problem I am having with `INP_RUN` is that the code runs immediately upon selection and then AGAIN upon CONFIRM.  The Menu_Test demo `myLEDCode` demonstrates the problem. If I am missing something please let me know. This library is great!

**Comment by bborncr** [comment]
I figured it out. My error. The bGet variable can be read to know if the action is a Get or Set.

**Comment by MajicDesigns** [comment]
Note the behavior of INP_RUN has changed in version 2.1.0
