### ISSUE TITLE
Limited Num of Menus/Items & Lite Version Request

### ISSUE THREAD

**Issue by ghost** [MajicDesigns/MD_Menu#14]
Is there a limit on the number of menus/items you can create? I need a little less than 700 in total but I'm getting some overflow errors.

Is there a way to increase the limitations to 1000? 

Also, would it be possible to have a stripped down 'Lite' version of the menu library? It would save even more memory as this library is amazing but contains way more than we might need. 

If we can manage and handle all of the data ourselves and then the library contains the bare minimum to hold only the IDs, names and just the INP_Run or 'user code' custom functions?

**Comment by MajicDesigns** [comment]
mnuId_t is currently defined as int8_t so it is limited to 255. Changing it to int16_t will make the limit 65535.

Do you have enough memory to hold all these items?
Without knowing you application, I would question how users will navigate so many items, even if organised into menu/submenu, etc.

For 'lite' version you can strip out as much as you want. It is pretty modular when you dig down into the code, so feel free to omit whatever you want.

**Comment by ghost** [comment]
Okay great thanks. Is the mnuId_t literally the only thing that will need changing? Does that cover both menus and items?

I'm on an Arduino mega 2560 at the moment. The application is to control many subtle effects and parameters on a guitar amp. There are over 60 built in effects in the amp, each with multiple parameters to tweak and edit. 

Unfortunately your code is too feature filled and complex for my current understanding to be stripping things away!

**Comment by MajicDesigns** [comment]
I think mnuId is the only change. I can't guarantee whether this propagates into some temporary variables that are sized incorrectly, so you need to change and try. I think I tested this change some time (years) ago but I can't remember.

If you can't strip it out your self then I suggest you just leave everything as it is.

**Comment by ghost** [comment]
I thank you. Very appreciative of your work and also the super quick responses! 

So I assume things like uint8_t _mnuItmCount in the header file will need to change too? And also the for loop counters in the cpp for in things like:
`MD_Menu::mnuInput_t* MD_Menu::loadInput(mnuId_t id)
// Find a copy the input item to the class private buffer
{
  for (uint8_t i = 0; i < _mnuItmCount; i++)`?

**Comment by MajicDesigns** [comment]
Everywhere that a mnuId_t is explicitly referenced will be ok if you just change the definition for mnuId in the header file. ie, it will take care of itself. 

The loop index and mnuItemCount are good examples of the unintended related sizes that will fail, as I mentioned in the previous response.

IK have had a look at the code and released version 2.1.1 which I think removes all the unintended consequences for mnuId_t. I also found c coupe of bugs in the process that have been fixed.

**Comment by ghost** [comment]
That sounds great, thanks!!

I think you also may need to change the uint8_t's to mnuId_t here too?:

**From MD_Menu.h**
`  MD_Menu(cbUserNav cbNav, cbUserDisplay cbDisp,
    const mnuHeader_t *mnuHdr, uint8_t mnuHdrCount,
    const mnuItem_t *mnuItm, uint8_t mnuItmCount,
    const mnuInput_t *mnuInp, uint8_t mnuInpCount);`
...and...
`uint8_t     _currMenu;                ///< Index of current menu displayed in the stack`
    
**From MD_Menu.cpp**
`MD_Menu::MD_Menu(cbUserNav cbNav, cbUserDisplay cbDisp,
                const mnuHeader_t *mnuHdr, uint8_t mnuHdrCount,
                const mnuItem_t *mnuItm, uint8_t mnuItmCount,
                const mnuInput_t *mnuInp, uint8_t mnuInpCount) :
                _mnuHdr(mnuHdr), _mnuHdrCount(mnuHdrCount),
                _mnuItm(mnuItm), _mnuItmCount(mnuItmCount),
                _mnuInp(mnuInp), _mnuInpCount(mnuInpCount),
                _timeout(0), _options(0)`

**Comment by MajicDesigns** [comment]
Yes, updated in v2.2.2.

**Comment by MajicDesigns** [comment]
OP has discussed problem fixed on Arduino forum.
