### ISSUE TITLE
Negative FLOAT Values bigger than -1 (e.g. -0.5) cause Problems. 

### ISSUE THREAD

**Issue by franz-ms-muc** [MajicDesigns/MD_Menu#15]
Negative FLOAT Values bigger than -1 (e.g. -0.5) cause Problems.

**Comment by franz-ms-muc** [comment]
it happens Here: 

```
_V.value / divisor
```

**Comment by franz-ms-muc** [comment]
if value = -70 and divisor = 100, then: result is 0, 

as there is no "-0" defined in INT, it loose the Sign.

**Comment by franz-ms-muc** [comment]
also here: 

```
bool sign = (v < 0);
```

**Comment by franz-ms-muc** [comment]
it would be true anyhow, as -1 is the first negative Number. 0 is not handeled correctly.

**Comment by franz-ms-muc** [comment]
[https://github.com/DiplomInformatikerFranzHoepfinger/MD_Menu/tree/feature/15-negative-float-values-bigger-than--1-](https://github.com/DiplomInformatikerFranzHoepfinger/MD_Menu/tree/feature/15-negative-float-values-bigger-than--1-)

possible Solution there !

**Comment by franz-ms-muc** [comment]
DiplomInformatikerFranzHoepfinger@8295f37

**Comment by MajicDesigns** [comment]
Fixed and rolled into v2.1.3
