### ISSUE TITLE
Compatability with Teensy?

### ISSUE THREAD

**Issue by polygonfuture** [MajicDesigns/MD_Menu#18]
Any word on compatability with teensy?

I'm getting the following errors on compilation:

`Arduino: 1.8.15 (Windows 10), TD: 1.54, Board: "Teensy 3.2 / 3.1, Serial, 96 MHz (overclock), Faster, US English"

In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/usb_keyboard.h:36:0,

                 from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/WProgram.h:58,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_build_601976/pch/Arduino.h:6,

                 from C:\Users\jmoor\Documents\Arduino\libraries\MD_Menu-main\src/MD_Menu.h:241,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test.h:3,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test_Nav.cpp:1:

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/keylayouts.h:180:33: error: expected identifier before '(' token

 #define KEY_DOWN                (  81  | 0xF000 )

                                 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:108:5: note: in expansion of macro 'KEY_DOWN'

     KEY_DOWN,        ///< Switch is detected as active (down)

     ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/keylayouts.h:180:33: error: expected '}' before '(' token

 #define KEY_DOWN                (  81  | 0xF000 )

                                 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:108:5: note: in expansion of macro 'KEY_DOWN'

     KEY_DOWN,        ///< Switch is detected as active (down)

     ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/keylayouts.h:180:36: error: expected unqualified-id before numeric constant

 #define KEY_DOWN                (  81  | 0xF000 )

                                    ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:108:5: note: in expansion of macro 'KEY_DOWN'

     KEY_DOWN,        ///< Switch is detected as active (down)

     ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/keylayouts.h:180:36: error: expected ')' before numeric constant

 #define KEY_DOWN                (  81  | 0xF000 )

                                    ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:108:5: note: in expansion of macro 'KEY_DOWN'

     KEY_DOWN,        ///< Switch is detected as active (down)

     ^

In file included from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test_Nav.cpp:118:0:

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:129:15: error: expected unqualified-id before 'void'

   MD_UISwitch(void);

               ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:129:15: error: expected ')' before 'void'

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:136:16: error: declaration of '~MD_UISwitch' as non-member

   ~MD_UISwitch() {};

                ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:150:26: error: 'virtual' outside class declaration

   virtual void begin(void) = 0;

                          ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:150:30: error: function 'void begin()' is initialized like a variable

   virtual void begin(void) = 0;

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:163:11: error: 'keyResult_t' does not name a type

   virtual keyResult_t read(void) = 0;

           ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:173:30: error: 'virtual' outside class declaration

   virtual uint8_t getKey(void) { return(_lastKey); };

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'uint8_t getKey()':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:173:41: error: '_lastKey' was not declared in this scope

   virtual uint8_t getKey(void) { return(_lastKey); };

                                         ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void setPressTime(uint16_t)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:192:42: error: '_timePress' was not declared in this scope

   inline void setPressTime(uint16_t t) { _timePress = t; };

                                          ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void setDoublePressTime(uint16_t)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:204:48: error: '_timeDoublePress' was not declared in this scope

   inline void setDoublePressTime(uint16_t t) { _timeDoublePress = t; enableDoublePress(true); };

                                                ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:204:92: error: 'enableDoublePress' was not declared in this scope

   inline void setDoublePressTime(uint16_t t) { _timeDoublePress = t; enableDoublePress(true); };

                                                                                            ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void setLongPressTime(uint16_t)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:220:46: error: '_timeLongPress' was not declared in this scope

   inline void setLongPressTime(uint16_t t) { _timeLongPress = t; enableLongPress(true); };

                                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:220:86: error: 'enableLongPress' was not declared in this scope

   inline void setLongPressTime(uint16_t t) { _timeLongPress = t; enableLongPress(true); };

                                                                                      ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void setRepeatTime(uint16_t)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:235:43: error: '_timeRepeat' was not declared in this scope

   inline void setRepeatTime(uint16_t t) { _timeRepeat = t; enableRepeat(true); };

                                           ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:235:77: error: 'enableRepeat' was not declared in this scope

   inline void setRepeatTime(uint16_t t) { _timeRepeat = t; enableRepeat(true); };

                                                                             ^

In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/WProgram.h:45:0,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_build_601976/pch/Arduino.h:6,

                 from C:\Users\jmoor\Documents\Arduino\libraries\MD_Menu-main\src/MD_Menu.h:241,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test.h:3,

                 from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test_Nav.cpp:1:

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void enableDoublePress(boolean)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:246:59: error: '_enableFlags' was not declared in this scope

   inline void enableDoublePress(boolean f) { (f) ? bitSet(_enableFlags, DPRESS_ENABLE) : bitClear(_enableFlags, DPRESS_ENABLE); };

                                                           ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:30: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:246:73: error: 'DPRESS_ENABLE' was not declared in this scope

   inline void enableDoublePress(boolean f) { (f) ? bitSet(_enableFlags, DPRESS_ENABLE) : bitClear(_enableFlags, DPRESS_ENABLE); };

                                                                         ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:49: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                                                 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void enableLongPress(boolean)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:259:57: error: '_enableFlags' was not declared in this scope

   inline void enableLongPress(boolean f) { (f) ? bitSet(_enableFlags, LONGPRESS_ENABLE) : bitClear(_enableFlags, LONGPRESS_ENABLE); };

                                                         ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:30: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:259:71: error: 'LONGPRESS_ENABLE' was not declared in this scope

   inline void enableLongPress(boolean f) { (f) ? bitSet(_enableFlags, LONGPRESS_ENABLE) : bitClear(_enableFlags, LONGPRESS_ENABLE); };

                                                                       ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:49: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                                                 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void enableRepeat(boolean)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:271:54: error: '_enableFlags' was not declared in this scope

   inline void enableRepeat(boolean f) { (f) ? bitSet(_enableFlags, REPEAT_ENABLE) : bitClear(_enableFlags, REPEAT_ENABLE); };

                                                      ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:30: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:271:68: error: 'REPEAT_ENABLE' was not declared in this scope

   inline void enableRepeat(boolean f) { (f) ? bitSet(_enableFlags, REPEAT_ENABLE) : bitClear(_enableFlags, REPEAT_ENABLE); };

                                                                    ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:49: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                                                 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: In function 'void enableRepeatResult(boolean)':

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:283:60: error: '_enableFlags' was not declared in this scope

   inline void enableRepeatResult(boolean f) { (f) ? bitSet(_enableFlags, REPEAT_RESULT_ENABLE) : bitClear(_enableFlags, REPEAT_RESULT_ENABLE); };

                                                            ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:30: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                              ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:283:74: error: 'REPEAT_RESULT_ENABLE' was not declared in this scope

   inline void enableRepeatResult(boolean f) { (f) ? bitSet(_enableFlags, REPEAT_RESULT_ENABLE) : bitClear(_enableFlags, REPEAT_RESULT_ENABLE); };

                                                                          ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/wiring.h:188:49: note: in definition of macro 'bitSet'

 #define bitSet(value, bit) ((value) |= (1UL << (bit)))

                                                 ^

In file included from C:\Users\jmoor\AppData\Local\Temp\arduino_modified_sketch_967663\Menu_Test_Nav.cpp:118:0:

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h: At global scope:

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:286:1: error: expected unqualified-id before 'protected'

 protected:

 ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:319:3: error: 'keyResult_t' does not name a type

   keyResult_t _kPush;     ///< storage for pushed key in FSM

   ^

C:\Users\jmoor\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:370:3: error: 'keyResult_t' does not name a type

   keyResult_t processFSM(bool swState, bool reset = false);

   ^

C:\Users\dada\Documents\Arduino\libraries\MD_UISwitch\src/MD_UISwitch.h:384:1: error: expected declaration before '}' token

 };

 ^

Error compiling for board Teensy 3.2 / 3.1.
`

**Comment by MajicDesigns** [comment]
Looks like KEY_DOWN is defined in the Teensy library somewhere. May be others but that is the first that comes up. One solution is to rename the MD_UISwitch definitions to avoid the clash.

If you use another key/switch detection library you can also avoid this.
