### ISSUE TITLE
Can an input object's callback be made aware of its ancestor (not just parent) ID(s)?

### ISSUE THREAD

**Issue by greiginsydney** [MajicDesigns/MD_Menu#19]
## IMPORTANT
Before submitting this issue
[x ] Have you tried using the latest version of the library?
[x ] Have you checked this has not already been submitted and/or resolved?
[x ] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
I'm hoping an input object might be able to determine not just its immediate parent, but its ancestors, but I haven't had any luck finding this in the documentation.

## Your Environment
**Library Version:** 2.1.3
**Arduino IDE version:** 1.8.13
**Hardware model/type:** Arduino Micro
**OS and Version:** Windows 10

## Steps to Reproduce

This is the setup I'm looking at implementing:
![image](https://user-images.githubusercontent.com/11004787/162916793-2ac5de31-b6cc-410d-aba0-411ccd41011a.png)

Objects "G" are multiple "channels" in my device, and they all share otherwise identical config parameters (H,J,K,L).

My problem here is that when in any of the INPUT callbacks for H, J, K or L I query the `MD_Menu::mnuId_t id`, all that's returned is the ID of the (in this example) INP_LIST and not which of the G's called it.

## Expected Behaviour
Ideally there would be a way for a "lower level"' input to gain insight into its ancestors.

## Actual Behaviour
`MD_Menu::mnuId_t id` returns the ID of the object that called it.

## Code Demonstrating the Issue
````

// Function prototypes for variable get/set functions
MD_Menu::value_t *mnuStepRqst  (MD_Menu::mnuId_t id, bool bGet);

<The defaults deleted for clarify here>


// Menu Headers --------
const PROGMEM MD_Menu::mnuHeader_t mnuHdr[] =
{
  { 10, "Main Setup Menu", 10, 12, 0 },
  { 11, "Setup Channels", 21, 27, 0 },
  { 12, "Setup Options", 140, 141, 0 },
 
  { 21, "Channel 1", 30, 37, 0 },
  { 22, "Channel 2", 30, 37, 0 },
  { 23, "Channel 3", 30, 37, 0 },
  { 24, "Channel 4", 30, 37, 0 },
  { 25, "Channel 5", 30, 37, 0 },
  { 26, "Channel 6", 30, 37, 0 },
  { 37, "Channel 7", 30, 37, 0 },
  { 28, "Channel 8", 30, 37, 0 },

};

// Menu Items ----------
const PROGMEM MD_Menu::mnuItem_t mnuItm[] =
{
  // Starting (Root) menu
  { 10, "Setup Channels", MD_Menu::MNU_MENU, 11 },
  { 12, "Setup Options", MD_Menu::MNU_MENU, 12 },
  // Select channel:
  { 21, "Channel 1", MD_Menu::MNU_MENU, 21 },
  { 22, "Channel 2", MD_Menu::MNU_MENU, 22 },
  { 23, "Channel 3", MD_Menu::MNU_MENU, 23 },
  { 24, "Channel 4", MD_Menu::MNU_MENU, 24 },
  { 25, "Channel 5", MD_Menu::MNU_MENU, 25 },
  { 26, "Channel 6", MD_Menu::MNU_MENU, 26 },
  { 27, "Channel 7", MD_Menu::MNU_MENU, 27 },
  { 28, "Channel 8", MD_Menu::MNU_MENU, 28 },
  
  // Channels submenu
  { 30, "Channel Info", MD_Menu::MNU_MENU, 30 }, // TODO
  { 31, "Enable/Disable", MD_Menu::MNU_INPUT, 11 }, // WORKS, but doesn't (yet?) report current setting - and not channel-aware
  { 32, "Set Steps", MD_Menu::MNU_INPUT, 83 }, // WORKS, but doesn't report current setting - and not channel-aware
  { 37, "Learn", MD_Menu::MNU_INPUT, 18 }, // TODO
 
};

// Input Items ---------
const PROGMEM char listSteps[] = "2|3|4|5|6|7|8";

const PROGMEM MD_Menu::mnuInput_t mnuInp[] =
{
  { 83, "Step count",  MD_Menu::INP_LIST, mnuStepRqst, 1, 0, 0, 0, 0, 0, listSteps }, // Set the number of steps
  { 11, "Enable", MD_Menu::INP_BOOL, mnuBValueRqst, 1, 0, 0, 0, 0, 0, nullptr },
};

// bring it all together in the global menu object
MD_Menu M(navigation, display,        // user navigation and display
  mnuHdr, ARRAY_SIZE(mnuHdr), // menu header data
  mnuItm, ARRAY_SIZE(mnuItm), // menu item data
  mnuInp, ARRAY_SIZE(mnuInp));// menu input data


// Callback code for Channel Step Count menu set/get input values
MD_Menu::value_t *mnuStepRqst(MD_Menu::mnuId_t id, bool bGet)
// Value request callback for list selection variable
{
  MD_Menu::value_t *r = &vBuf;
  Serial.print("\n - Channel step count GOT TO HERE");
  Serial.print(F("\nCalling ID was "));
  Serial.print(id);
  if (bGet)
    vBuf.value = fruit;
  else
  {
    fruit = vBuf.value;
    Serial.print(F("\nList index changed to "));
    Serial.print(fruit);
  }

  return(r);
}

````

And the Output when I navigate:
Main Menu > Channel Setup > Channel 'n' > Step Count >

```
18:41:48.176 ->  - Channel step count GOT TO HERE
18:41:48.176 -> Calling ID was 83
```

<br>
(Awesome library BTW Marco!)
<br>

\- Greig.

**Comment by MajicDesigns** [comment]
The short answer is not without a major rewrite of the library. The reason is that by inserting node 'I' you have violated the rule that this is a tree, which is built into the whole way the library works.

The way around what you want to do is to have G1 with leaves H1, J1, K1, L1, G2 with leaves H2, J2, K2, L2, etc (ie, you need to unroll the whole thing out). This means a duplication in the menu setup parameters but does not mean that you need more code in the callback. If you arrange the IDs for H1, H2, ... Hn to be consecutive, in the callback you can extract the channel number by Hx-H1 and reuse the same code for all channels. Similary for J, K, L.

**Comment by greiginsydney** [comment]
Thanks for the speedy response Marco.

I was hoping to avoid the menu duplication, but that's done the trick.

As my suggestion would involve a major re-write and there's a way around it, it's probably safe to close this issue.

\- G.
