### ISSUE TITLE
Is there a better way to hold isInMenu==true while loop() writes to the screen?

### ISSUE THREAD

**Issue by greiginsydney** [MajicDesigns/MD_Menu#20]
## IMPORTANT
Before submitting this issue
[x ] Have you tried using the latest version of the library?
[x ] Have you checked this has not already been submitted and/or resolved?
[x ] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
Is there a better way for me to be able to hold the menu 'active' (`isInMenu==true`) and run code in loop() that writes to the screen?

My goal here is to have an INPUT TYPE that displays nothing on the screen in the menu code, allowing loop() to write 'monitor-type' messages to the screen until the user aborts.

I've already kludged it by doing what I want in the callback code for `INP_RUN`, and the kludge is that it required me to write my own read and debounce code for the ESC button, rather than rely on `userNavAction_t` to do that for me.

## Your Environment
**Library Version:** 2.1.3
**Arduino IDE version:** 1.8.13
**Hardware model/type:** Arduino Micro
**OS and Version:** Windows 10

## Steps to Reproduce
n/a

## Expected Behaviour
The menu is active (isInMenu==true) and userNavAction_t still runs controlling when we abort.

## Actual Behaviour
A kludged version of the above.

## Code Demonstrating the Issue
```

// Function prototypes for variable get/set functions
MD_Menu::value_t *sniffRF(MD_Menu::mnuId_t id, bool bGet);

const PROGMEM MD_Menu::mnuInput_t mnuInp[] =
{
  { 44, "Confirm", MD_Menu::INP_RUN, sniffRF, 0, 0, 0, 0, 0, 0, nullptr },
}

//Callback to clear the screen, enable RF Rx and output any received codes
MD_Menu::value_t *sniffRF(MD_Menu::mnuId_t id, bool bGet)
{
  
  if (bGet)
  {
    //Do nothing on the GET. We'll hold in the SET until the user aborts.
  }
  else
  {
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("Waiting...");
    lcd.setCursor(0, 1);
    lcd.print("(ESC to exit)");
    //M.setTimeout(0);    // Note to future Greig: we don't need to do this because we're blocking here. The backlight timeout and menu timeout are inactive
    
    while (true)
    {
      readSwitches();
      if (switchPressed[0] == true)
      {
        switchPressed[0] = false;
        break;
      }
      else
      {
        // Magic happens here>
      }
    }
  }
  //M.setTimeout(MENU_TIMEOUT);   // As explained above. Unnecessary.
  return(nullptr);
}
```
<br>

Thanks.

\- Greig.

**Comment by MajicDesigns** [comment]
Did you try setting the menu timeout to 0?

**Comment by greiginsydney** [comment]
Well that's embarassing! I'd overcomplicated that terribly Thanks!

**Comment by greiginsydney** [comment]
Actually that's still a _tiny_ bit kludgy, because when you ESC, it takes you back up a level in the menu tree, rather than re-presenting the menu option that you've just escaped from. I'm OK working with that at the moment though.

**Comment by greiginsydney** [comment]
For anyone following, here's how I've handled this:

- I've replaced my `INP_RUN` with a dummy `INP_LIST`.
- in the callback for the `INP_LIST` I set a global flag to indicate this mode has been invoked.
- in `userNavAction_t` I disable INC, DEC & SEL if the flag's set.
- in loop() I look for the flag AND that we're in EditMode, then take over writing to the screen
- if the flag is set and we are no longer in EditMode, the user has ESC'd. Clear the flag & reinstate M.setTimeout

With the above config the menu handling is correct: ESC takes you back one level.

Code extracts:

```
bool sniffRfMode = false;                 // We set this when the menu option is selected so loop() can take over
```
<hr>

```
const PROGMEM MD_Menu::mnuInput_t mnuInp[] =
{
  { 44, "DummyINP",  MD_Menu::INP_LIST, sniffRF, 1, 0, 0, 0, 0, 0, listSteps }, // A hidden INP to trigger "IsInEdit".
}
```

<hr>

```
//Callback to clear the screen, enable RF Rx and output any received codes
MD_Menu::value_t *sniffRF(MD_Menu::mnuId_t id, bool bGet)
{
  //We hold in the menu but loop() detects this and takes over
  sniffRfMode = true;
  M.setTimeout(0);

  // This tricks the menu into thinking we're InEdit mode, which I use to detect we've not left this menu
  MD_Menu::value_t *r = &vBuf;
  return(r);
}
```

<hr>

```
loop()
{

  if (sniffRfMode)
    {
      if (!M.isInEdit())
      {
        sniffRfMode = false;
        M.setTimeout(MENU_TIMEOUT);
        Serial.println("EXITED sniff RF mode");
      }
      else
      {
        lcd.clear();
        Serial.println("sniff RF mode");
        //TODO: stuff happens here
      }
    }
}
```

<br>

Marco I only reopened this issue so you get a notification. Please close it - no action required.
