### ISSUE TITLE
[Feature request]: Add potentiometer as input device

### ISSUE THREAD

**Issue by alf45tar** [MajicDesigns/MD_Menu#4]
Marco, thanks you for your great libraries MD_Menu and MD_UISwitch. I am using them for my projects saving me a lot of development time.

Please add to your long to-do list this request: moving from min to max of a input value (int, float, etc.) using a pot. 

Thanks

**Comment by MajicDesigns** [comment]
Feature is included in v2.10 release.

New INP_EXT allows user to provide numeric input from an external source handled by user code.
