### ISSUE TITLE
[Feature Request]: Option to run function without confirmation

### ISSUE THREAD

**Issue by dogtopus** [MajicDesigns/MD_Menu#7]
Currently it is not possible to add a menu entry that calls a function without user confirmation (`INP_RUN` goes through the regular get/set process so it acts like a confirmation and there's no way to skip it). While confirmation makes sense on some functions (something dangerous like reset settings) it is purely annoying on others.

**Comment by MajicDesigns** [comment]
Feature will be released in version 2.1.0.

Value callback with get == true determines whether the confirmation is required or not. Return nullptr -> confirm, non nullptr -> do not confirm. This should not break existing implementations.
