### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by tarbear123** [MajicDesigns/MD_Menu#9]
do i put the names i want in these?
// Menu Headers --------
const PROGMEM MD_Menu::mnuHeader_t mnuHdr[] =
{
  { 10, "MD_Menu", 10, 12, 0 },
  { 11, "Input Data", 20, 27, 0 },
  { 12, "LED Menu", 40, 41, 0 },
};
do i put the name of the games i want in the " "
// Menu Items ----------
const PROGMEM MD_Menu::mnuItem_t mnuItm[] =
{
  // Starting (Root) menu
  { 10, "Input Test", MD_Menu::MNU_MENU, 11 },
  { 12, "LED", MD_Menu::MNU_MENU, 12 },
  // Input Data submenu
  { 20, "Fruit List", MD_Menu::MNU_INPUT, 10 },
  { 21, "Boolean", MD_Menu::MNU_INPUT, 11 },
  { 22, "Integer 8", MD_Menu::MNU_INPUT, 12 },
  { 23, "Integer 16", MD_Menu::MNU_INPUT, 13 },
  { 24, "Integer 32", MD_Menu::MNU_INPUT, 14 },
  { 25, "Hex 16", MD_Menu::MNU_INPUT, 15 },
  { 26, "Float", MD_Menu::MNU_INPUT, 16 },
  { 27, "Eng Unit", MD_Menu::MNU_INPUT, 17 },
  { 28, "Reset Menu", MD_Menu::MNU_INPUT, 18 },
  // LED  
  { 40, "Turn Off", MD_Menu::MNU_INPUT, 40 },
  { 41, "Turn On", MD_Menu::MNU_INPUT, 41 },
};
and what are these used for?
const PROGMEM MD_Menu::mnuInput_t mnuInp[] =
{
  { 10, "List", MD_Menu::INP_LIST, mnuLValueRqst, 6, 0, 0, 0, 0, 0, listFruit }, // shorter and longer list labels
  { 11, "Bool", MD_Menu::INP_BOOL, mnuBValueRqst, 1, 0, 0, 0, 0, 0, nullptr },
  { 12, "Int8", MD_Menu::INP_INT, mnuIValueRqst, 4, -128, 0, 127, 0, 10, nullptr },
  { 13, "Int16", MD_Menu::INP_INT, mnuIValueRqst, 4, -32768, 0, 32767, 0, 10, nullptr },  // test field too small
  { 14, "Int32", MD_Menu::INP_INT, mnuIValueRqst, 6, -66636, 0, 65535, 0, 10, nullptr },
  { 15, "Hex16", MD_Menu::INP_INT, mnuIValueRqst, 4, 0x0000, 0, 0xffff, 0, 16, nullptr },  // test hex display
  { 16, "Float", MD_Menu::INP_FLOAT, mnuFValueRqst, 7, -10000, 0, 99950, 0, 10, nullptr },  // test float number
  { 17, "Eng", MD_Menu::INP_ENGU, mnuEValueRqst, 7, 0, 0, 999000, 3, 50, engUnit },  // test engineering units number
  { 18, "Confirm", MD_Menu::INP_RUN, myCode, 0, 0, 0, 0, 0, 10, nullptr },

  { 40, "Confirm", MD_Menu::INP_RUN, myLEDCode, 0, 0, 0, 0, 0, 0, nullptr },  // test using index in run code
  { 41, "Confirm", MD_Menu::INP_RUN, myLEDCode, 0, 0, 0, 0, 0, 0, nullptr },
};

**Comment by MajicDesigns** [comment]
> do i put the name of the games i want in the " "
Yes

> and what are these used for?
Suggest that you read the library documentation that is in the docs folder.

**Comment by tarbear123** [comment]
do i need these if i create a game menu?
 // Input Data submenu
{ 20, "Fruit List", MD_Menu::MNU_INPUT, 10 },
{ 21, "Boolean", MD_Menu::MNU_INPUT, 11 },
{ 22, "Integer 8", MD_Menu::MNU_INPUT, 12 },
{ 23, "Integer 16", MD_Menu::MNU_INPUT, 13 },
{ 24, "Integer 32", MD_Menu::MNU_INPUT, 14 },
{ 25, "Hex 16", MD_Menu::MNU_INPUT, 15 },
{ 26, "Float", MD_Menu::MNU_INPUT, 16 },
{ 27, "Eng Unit", MD_Menu::MNU_INPUT, 17 },
{ 28, "Reset Menu", MD_Menu::MNU_INPUT, 18 },
// LED
{ 40, "Turn Off", MD_Menu::MNU_INPUT, 40 },
{ 41, "Turn On", MD_Menu::MNU_INPUT, 41 },
};

**Comment by MajicDesigns** [comment]
I can't tell if you need it or not as that depends on your implementation. Those are from the example program to show how each different type of menu options/entries are defined and used. I would expect that you will just use what you need and perhaps only a few of the menu types.

**Comment by tarbear123** [comment]
i did this to get it to pop up
if (id == 10)
  {
  void setup()
{
  lcd.begin(16, 2);              // start the library
  lcd.setCursor(0, 0);
  lcd.print("press select to dice"); // print a simple message
  randomSeed(analogRead(1));
}

void loop()
{
  long diceOne = random(1, 7);
  long diceTwo = random(1, 7);
  int total = diceOne + diceTwo;
  
  lcd_key = read_LCD_buttons();  // read the buttons

  if (lcd_key == btnSELECT) {
    lcd.clear();
    lcd.setCursor(7, 0);
    lcd.print( diceOne);
    lcd.setCursor(7, 1);
    lcd.print( diceTwo );

analogRead (lcd_key == btnSELECT);
delay (100);
analogRead (lcd_key == btnSELECT);
delay (100);

   
      if ( total == 2,3,4,5,6,8,9,10,11,12 ) {
      lcd.clear();
      lcd.setCursor(7, 0);
      lcd.print( total );
      
    if ( total == 7 ) {
      lcd.clear();
      lcd.setCursor(7, 0);
      lcd.print( "7");
      lcd.setCursor(3, 1);
      lcd.print("The robber");


if (total == 7 > 1){
lcd.clear();
lcd.setCursor(7,0);
lcd.print("2,3,4,5,6,8,9,10,11,12");

 }
}
}
}
}
  return(r);

**Comment by MajicDesigns** [comment]
And I am guessing that it does not work? Your issue is not with using the libraries. It looks like you are missing key knowledge of how to write code.

If you need programming help I would refer you to the arduino.cc or similar forums that are designed for this. This site is for library issues and bugs rather than general programming help. I just don't have the time to be teaching individuals 1-on-1 how to program.

I would also advise looking at some Arduino tutorials if you have not already done so. Programming is fun but will be frustrating if you don't get the basics in place before you launch in complexity.

Once you have some mastery, my suggestion is to start with one of the Menu examples and make changes from there rather than invent things that will not work. That way when it 'breaks' you know the last change you make did the damage.

**Comment by tarbear123** [comment]
I need help plz
Arduino: 1.8.7 (Windows 10), TD: 1.45, Board: "Arduino/Genuino Uno"

In file included from C:\Users\taran\AppData\Local\Temp\arduino_modified_sketch_129719\Menu_LCD-Shield.ino:19:0:

C:\Users\taran\Documents\Arduino\libraries\MD_Menu-master\src/MD_Menu.h:273:3: warning: 'typedef' was ignored in this declaration

   };

   ^

C:\Users\taran\Documents\Arduino\libraries\MD_Menu-master\src/MD_Menu.h:338:3: warning: 'typedef' was ignored in this declaration

   };

   ^

C:\Users\taran\Documents\Arduino\libraries\MD_Menu-master\src/MD_Menu.h:368:3: warning: 'typedef' was ignored in this declaration

   };

   ^

C:\Users\taran\Documents\Arduino\libraries\MD_Menu-master\src/MD_Menu.h:396:3: warning: 'typedef' was ignored in this declaration

   };

   ^

C:\Users\taran\Documents\Arduino\libraries\MD_Menu-master\src/MD_Menu.h:412:3: warning: 'typedef' was ignored in this declaration

   };

   ^

Menu_LCD-Shield:151:3: error: expected '}' before 'MD_Menu'

   MD_Menu M(navigation, display,        // user navigation and display

   ^

C:\Users\taran\AppData\Local\Temp\arduino_modified_sketch_129719\Menu_LCD-Shield.ino:151:3: warning: initializer-string for array of chars is too long [-fpermissive]

Menu_LCD-Shield:151:3: error: expected ',' or ';' before 'MD_Menu'

Multiple libraries were found for "LiquidCrystal.h"
 Used: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal
 Not used: C:\Users\taran\Documents\Arduino\libraries\fmalpartida-new-liquidcrystal-638d2cc44569
exit status 1
expected '}' before 'MD_Menu'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by MajicDesigns** [comment]
This is saying there is a problem with the code you are compiling. Does the compiler work with the examples supplied? If yes then the problem is with your code. (See previous comments). If no, tell me which example you are compiling.

The only error listed is
`Menu_LCD-Shield:151:3: error: expected '}' before 'MD_Menu'`
The others are warnings and can be ignored. This tells you that your code is not formatted properly.
